# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node CI

on:
  push:
    branches:
      - dev
  pull_request:
    branches: 
      - dev

jobs:
  server_build: 

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Packages
      run: npm i
      working-directory: ./server
      
#     - name: Build
#       run: npm run build --if-present
  
    - name: Test Linting
      run: npm run lint
      working-directory: ./server
